### ISSUE TITLE
Lack of maintenance

### ISSUE THREAD

**Issue by hajapy** [conda-forge/tensorflow-feedstock#107]
This feedstock has stagnated relative to the upstream project, which I believe is largely due to how complex tensorflow is to build within conda. We have also failed to really solve the gpu/cuda case which is most critical for this project.

I’m wondering what next steps people think we should take.

This is a highly downloaded package - it would be great for the community if we could keep it up to date and deliver on variants with gpu support.

**Comment by derekschinke** [comment]
Agreed, I was very surprised by how out of date this package was. I moved to conda-forge because it was supposed to have faster updates than the anaconda and main channels, but as I go deeper it seems like that's not the case.

**Comment by isuruf** [comment]
@derekschinke, complaining doesn't help. PRs are always welcome.

**Comment by derekschinke** [comment]
@isuruf  "complaining" definitely does, because it boosts the issue to people like you (like my comment apparently accomplished) who are definitely more capable than I am of addressing this issue.

**Comment by hajapy** [comment]
This issue is intended to be a call for help and input. We have had a few fantastic contributors advance the state of this feedstock, but large challenges remain unsolved. 

Defaults does seem to have a better solution, but that seems like a good chunk of work for @jjhelmus and others to maintain. Perhaps we could take advantage of some of their solution here?

Maybe we could engage with tensorflow devs and/or nvidia more actively to see if there is any support they could lend?

**Comment by adrianchia** [comment]
I was trying to rebuild the tensorflow 2.x based on https://github.com/AnacondaRecipes/tensorflow_recipes, a few things I noticed is that: 

1. it uses Bazel 3.1.0, which is available in the default conda channel and available for Linux and Windows, but not OSX

2. build time could take more than 6 hours, which is longer than the maximum provided by azure pipelines.

**Comment by njzjz** [comment]
A few days ago, I successfully built both CPU and GPU version of TensorFlow 2.3 C++ interface, i.e. `libtensorflow_cc`, based on the default channel. I upload my recipe to https://github.com/deepmd-kit-recipes/libtensorflow_cc-feedstock/tree/master/recipe. It may be useful if anyone is interested in it. I created the repository with conda-forge build tools, but I finally built it on my computer since the build time is too long.

**Comment by asford** [comment]
@hajapy Would you all be open to more limited maintenance to help cover the cases that *aren't* being tackled by the current defaults? For example, pushing the existing OSX packaging strategy here ("repackage the upstream wheel build") forward for the 2.* release series?

Recreating the hard work already present in defaults for the windows and linux builds seems to be of limited value, but there's a big gap in `tensorflow>=2`-on-`osx-64`-on-`conda` right now we could tackle.

**Comment by isuruf** [comment]
@asford, IMO, that's fine. Please send a PR even if it's not working fully.

**Comment by xhochy** [comment]
Fixed by #110
