### ISSUE TITLE
Update to 2.4.3 to catch a ton of CVE mitigations?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/tensorflow-feedstock#126]
Tensorflow 2.4.3 was [released](https://github.com/tensorflow/tensorflow/releases/tag/v2.4.3) a few hours ago with a spectacular amount of CVEs attached against old versions. Should we rebuild for this more quickly than trying to figure out the corresponding 2.5.1 build?

@conda-forge/tensorflow

**Comment by xhochy** [comment]
Do the old patches still apply?

**Comment by h-vetinari** [comment]
Patches from current master branch here rebased cleanly from 2.4.0 to 2.4.3.
