### ISSUE TITLE
Create cuda branch

### ISSUE THREAD

**Issue by izahn** [conda-forge/tensorflow-feedstock#134]
As discussed in https://github.com/conda-forge/tensorflow-feedstock/pull/120 and https://github.com/conda-forge/tensorflow-feedstock/pull/131 it has proven very difficult to produce cuda-enabled builds based on the master branch of this repository. I am therefore requesting the creation of a separate `cuda` (or `gpu`, etc., as you prefer) branch from which we can produce cuda-enabled builds. I have branches ready to PR at https://github.com/izahn/tensorflow-feedstock/tree/cuda_2.5.1 and https://github.com/izahn/tensorflow-feedstock/tree/cuda_2.6.0, I just need a suitable branch here PR to.

**Comment by isuruf** [comment]
I don't think we are going to go with that branch given that it is not using the conda packages and vendor lots of packages.

**Comment by izahn** [comment]
OK, I'll just keep hosting them at https://anaconda.org/izahn I guess. Too bad, I think a lot of people would benefit from having a cuda enabled tensorflow on conda-forge.

**Comment by h-vetinari** [comment]
I'm sorry that your work could not (yet!) be leveraged for conda-forge. There are efforts underway (not yet coalesced...) to get the CI beefed up enough to build this according to the CF-requirements, which would massively alleviate the current bottleneck of manual rebuilds (allowing more iteration on the recipe & by more contributors). It's a slog for everyone, and the trade-offs are not always crystal-clear, but I tend to agree with Isuru that it's better to do it right (even if it's slower).

I'm hoping someone can iterate on your PR + Isuru's [suggestion](https://github.com/conda-forge/tensorflow-feedstock/pull/120#issuecomment-933775137). I might get around to it in a couple weeks.

**Comment by izahn** [comment]
Thanks @h-vetinari and @isuruf I totally get it, and thanks for all your efforts and leadership in the conda-forge community.

**Comment by hmaarrfk** [comment]
I think that the work is close to being merged in.

Thanks for trailblazing!
