### ISSUE TITLE
Package pinnings

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/tensorflow-feedstock#151]
This package seems to have a few harsh pinnings that downgrade and upgrade other packages.

For example, installing the newly built package, that unpins protobuf and grpc-cpp, 

I guess the following downgrades:
```
  - astroid                        2.8.2  py39hf3d152e_0          installed
  + astroid                        2.7.3  py39hf3d152e_0          conda-forge/linux-64      Cached
  - black                         21.9b0  pyhd8ed1ab_0            installed
  + black                         21.7b0  pyhd8ed1ab_0            conda-forge/noarch        Cached
  - bokeh                          2.4.1  py39hf3d152e_1          installed
  + bokeh                          2.3.3  py39hf3d152e_0          conda-forge/linux-64      Cached
  - decorator                      5.1.0  pyhd8ed1ab_0            installed
  + decorator                      4.4.2  py_0                    conda-forge/noarch        Cached
  - h5py                           3.3.0  nompi_py39h98ba4bc_100  installed
  + h5py                           3.1.0  nompi_py39h25020de_100  conda-forge/linux-64        1 MB
  - numpy                         1.21.2  py39hdbf815f_0          installed
  + numpy                         1.19.5  py39hdbf815f_2          conda-forge/linux-64        5 MB
  - pylint                        2.11.1  pyhd8ed1ab_0            installed
  + pylint                        2.10.2  pyhd8ed1ab_0            conda-forge/noarch        Cached
  - six                           1.16.0  pyh6c4a22f_0            installed
  + six                           1.15.0  pyh9f0ad1d_0            conda-forge/noarch        Cached
  - typing-extensions           3.10.0.2  hd8ed1ab_0              installed
  + typing-extensions            3.7.4.3  0                       conda-forge/noarch        Cached
  - typing_extensions           3.10.0.2  pyha770c72_0            installed
  + typing_extensions            3.7.4.3  py_0                    conda-forge/noarch        Cached
```

## Reference issues:

- [ ] numpy pinned to 1.19.2: https://github.com/tensorflow/tensorflow/issues/47691#issuecomment-889506604
     - https://github.com/tensorflow/tensorflow/issues/50204#issuecomment-858939248

https://github.com/conda-forge/tensorflow-feedstock/pull/142

**Comment by h-vetinari** [comment]
It should be possible to remove the pins for all but numpy, I'm guessing?

**Comment by hmaarrfk** [comment]
From comments in the tensorflow source, it seems that they were trying to help pip solve dependencies for astunparse. However, from the github issues on astunparse, it seems that it isn't necessary:
simonpercivall/astunparse#65

I've also audited the tensorflow code directly, for v2.6.2 and master, and it seems that wheel is never imported directly in the python source

Would it be acceptable to remove the pinning on wheel:
tensorflow/tensorflow#53308 (comment)

**Comment by hmaarrfk** [comment]
I believe Tensorflow 2.7.0 solves many of these issues. They just released their pinnings to something much more reasonable. Closing this for now.
