### ISSUE TITLE
building tf 2.7.0

### ISSUE THREAD

**Issue by ngam** [conda-forge/tensorflow-feedstock#169]
I used this repo to build tf 2.7.0 version on M1 osx-arm64 (see here: https://anaconda.org/ngam/tensorflow). Just sharing some thoughts to help accelerate the process: 
-- need keras 2.7.0 (I guess that's why you're still waiting? https://github.com/conda-forge/keras-feedstock/pull/54 I managed to build it fine on my machine as well and so all good)
-- patches need fixing (some of the patches no longer needed; can share more details)
-- deps need updating (a total mess!)

However, most importantly! All the tests passed except for the tf-estimator because of a dependency on `tensorflow-io-gcs-filesystem` --- interestingly, that shows up like this:

```bash
tensorflow 2.7.0 requires tensorflow-io-gcs-filesystem, which is not installed.
Tests failed for tensorflow-estimator-2.7.0-cpu_py39h91c69d6_0.tar.bz2 - moving package to /../../tensorflow-feedstock/miniforge3/conda-bld/broken
``` 

(I still uploaded it for testing --- it seems to work fine despite the tests failing). Just giving you heads up. I have no idea if this io-gcs-filesystem is a new thing or not. I guess maybe you need to build it as well? https://github.com/tensorflow/io 

Good luck, let me know if you'd like any help :)

**Comment by h-vetinari** [comment]
Thanks for looking at this.



> deps need updating (a total mess!)

Doesn't look too bad [here](https://github.com/tensorflow/tensorflow/blame/v2.7.0/tensorflow/tools/pip_package/setup.py). Finally a lot of upper bounds are lifted!

**Comment by hmaarrfk** [comment]
This is likely failing at the `pip check` stage.

Lets just patch out the explicit dependency:

```patch
diff --git a/tensorflow/tools/pip_package/setup.py b/tensorflow/tools/pip_package/setup.py
index 26306e43aaf..2c36e011fc6 100644
--- a/tensorflow/tools/pip_package/setup.py
+++ b/tensorflow/tools/pip_package/setup.py
@@ -106,7 +106,7 @@ REQUIRED_PACKAGES = [
     # Keras release is not backward compatible with old tf release, and we have
     # to make the version aligned between TF and Keras.
     'keras >= 2.7.0rc0, < 2.8',
-    'tensorflow-io-gcs-filesystem >= 0.21.0',
+    # 'tensorflow-io-gcs-filesystem >= 0.21.0',
 ]
```
