### ISSUE TITLE
Make 0.8.0 pre-release

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/tensorflow-feedstock#2]
tensorflow has made a [0.8.0 pre-release (0.8.0rc0)](https://github.com/tensorflow/tensorflow/releases/tag/v0.8.0rc0) for which google is supplying [whl files](https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#pip-installation).  Is it worth while to create conda packages for these or should we wait until the official 0.8.0 version is released?

**Comment by pelson** [comment]
> Is it worth while to create conda packages for these or should we wait until the official 0.8.0 version is released?

Good question. In general, I wouldn't want a user to ```conda update``` and get a pre-release accidentally. Maybe we need another channel which allows us to put experimental things...

**Comment by jjhelmus** [comment]
Closing. Tensorflow 0.8.0 has been released which will need a build.  I will open a new issue to track this.
