### ISSUE TITLE
Unable to install tensorflow on windows 10

### ISSUE THREAD

**Issue by jerrykur** [conda-forge/tensorflow-feedstock#21]
I am trying to install tensorflow into a virtualenv using the command, _conda install -c conda-forge tensorflow_ . This returns the following errors:

PackageNotFoundError: Package not found: '' Package missing in current win-64 channels:
  - tensorflow

Close matches found; did you mean one of these?

    tensorflow: xtensor

You can search for packages on anaconda.org with

    anaconda search -t conda tensorflow

Any idea why?

**Comment by jjhelmus** [comment]
Tensorflow does not yet support Windows, hence the lack of a conda package on that operating system.  Support for Windows seems to be in the works, tensorflow/tensorflow#17. Once a stable release of the package is made which supports Windows it should be possible to create a Windows conda package, until then installing on Windows will not be possible.

**Comment by jjhelmus** [comment]
Tensorflow `0.12.0rc0` adds support for Windows (64-bit and Python 3.5 only).  Once complete, PR #23 will add a win-64 conda package.
