### ISSUE TITLE
can we accelerate the builds here with remote caching?

### ISSUE THREAD

**Issue by ngam** [conda-forge/tensorflow-feedstock#233]
### Comment:

https://bazel.build/docs/remote-caching

(haven't looked into this thoroughly, so just leaving it here for now)

**Comment by ngam** [comment]
I envision the following:

We can likely set this up here in the open using github packages, I can do that in the ocming weeks. 

https://github.com/buchgr/bazel-remote/#docker

The idea is that, one of us can do a build (e.g. hmaarrfk, xhochy, etc.) and then the build cache will be available for all here through ghcr.io, then the ci itself can also use this cache and we may --- just _may_ --- be able to start building with the 6-hour limit!

**Comment by ngam** [comment]
For an example of ghcr-based caching, see my repo: https://github.com/ngam/ocis.

You will see inside the cgc container, it has the tag "buildcache" as well as latest: https://github.com/ngam/ocis/pkgs/container/cgc

The idea is that, when you do a build, you won't need to pull content again, etc.  see example: https://github.com/ngam/ocis/actions/runs/2298175118 (one of them flies)

and the underlying workflows: https://github.com/ngam/ocis/blob/b9ada832c87902b6255717e56212296958f1294f/.github/workflows/cgc_rel.yml#L68-L69

**Comment by ngam** [comment]
(I noticed that my local building is much faster the second iteration, so I assume some level of caching is automated --- though I had to delete stuff as /tmp is way too full, so it slowed down again...)

**Comment by ngam** [comment]
cc @xhochy @hmaarrfk

**Comment by hmaarrfk** [comment]
I'm really not a fan of caching builds. It introduces an other bootstrapping process and yet an other point of failure.

Honestly though, the limits on build time for your personal project project and for conda forge are the same. So feel free to set things up in your own repo and show that caching can help. A demo is worth 1000000 proposals. If it works, I'm much much more likely to change my mind.

For what it is worth, whether you tag me or not i get a notification. I think it is most appropriate to tag if:
* I already engaged on the subject and the conversation is jumping issues/repos.
* I haven't responded in some time (5 days? 7days?)

I'm somewhat maximized on the effort I'm putting toward tensorflow. So tagging me on many questions doesn't do much to accelerate things.

**Comment by ngam** [comment]
> For what it is worth, whether you tag me or not i get a notification. I think it is most appropriate to tag if:

Thanks, got it. Sorry for bothering you! Just wanted to make sure you're in the loop, but I will get that in mind going forward 😅 

> A demo is worth 1000000 proposals. If it works, I'm much much more likely to change my mind

Yes, I will try to do that soon!
