### ISSUE TITLE
TensorFlow v0.12.0 released

### ISSUE THREAD

**Issue by babhishek21** [conda-forge/tensorflow-feedstock#25]
TensorFlow v0.12.0 has been released. Time to update! See [here](https://github.com/tensorflow/tensorflow/releases)

BTW can anyone tell me how you determine if there any changes to the build requirements for the original source? Maybe I can update the recipe by myself next time.

**Comment by ivoflipse** [comment]
This version has also been released for Windows. Also any ideas on how to deal with the GPU support? As they are the same package, though it requires CUDA

**Comment by babhishek21** [comment]
When using `pip`, the package name is `tensorflow-gpu` instead of `tensorflow`. I think a separate feedstock is the way to go.

**Comment by QtRoS** [comment]
Guys, how can I help?
I want to get latest version ASAP :)

**Comment by ivoflipse** [comment]
@QtRoS fork this repo, update the recipe and get the CI to pass. I believe this one repackages the pip package so adding Windows support should be easy

**Comment by QtRoS** [comment]
@ivoflipse can you take a look?
[https://github.com/conda-forge/tensorflow-feedstock/pull/26]()

**Comment by babhishek21** [comment]
This should be closed in the light of PR #26.

**Comment by jjhelmus** [comment]
I'll close this once #27 is merged, since that will complete the addition of version 0.12.1

**Comment by ivoflipse** [comment]
Thanks for the Windows support @jhelmus!

**Comment by jjhelmus** [comment]
The windows package has shown up on the [conda-forge Anaconda cloud channel](https://anaconda.org/conda-forge/tensorflow/files?version=0.12.1).  I think this completes the release of `0.12.1`.

Closing this issue!
