### ISSUE TITLE
Cuda support dropped for all but 11.2

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/tensorflow-feedstock#272]
### Comment:

In https://github.com/conda-forge/tensorflow-feedstock/pull/266 the decision was made to drop Cuda 10.2, 11.0, 11.1.

*  Cuda 10.2 Dropped as it is seemingly unsupported
*  Cuda 11.0 and 11.1 dropped due to failing builds for 11.1 and no resources to investigate this further. PRs that fix this are welcome.

PRs to add support for missing cuda versions are welcome.

**Comment by jakirkham** [comment]
Looks like this feedstock is on CUDA 12. Should we close this issue?
