### ISSUE TITLE
ImportError: libflatbuffers.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bryant1410** [conda-forge/tensorflow-feedstock#275]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I install the (latest) tensorflow 2.10 from conda-forge, however I'm getting that `libflatbuffers` can't be found. At first I thought it was my env, but I tried with a fresh one and I'm still getting the same issue.

I installed my env with `mamba create -n test python conda-forge::tensorflow` (mamba 0.25.0), I run `python -c "import tensorflow"` and I get:

```
Traceback (most recent call last):
  File "/home/sacastro/.pyenv/versions/miniconda3-latest/envs/test/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libflatbuffers.so.2: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sacastro/.pyenv/versions/miniconda3-latest/envs/test/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/sacastro/.pyenv/versions/miniconda3-latest/envs/test/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/sacastro/.pyenv/versions/miniconda3-latest/envs/test/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/home/sacastro/.pyenv/versions/miniconda3-latest/envs/test/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libflatbuffers.so.2: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
```

Note I have `flatbuffers` and `python-flatbuffers` installed. Though I'm not sure they provide this library file.

### Installed packages

```shell
# packages in environment at /home/sacastro/.pyenv/versions/miniconda3-latest/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   1.2.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.1           py310h7f8727e_1  
aiosignal                 1.2.0              pyhd3eb1b0_0  
astunparse                1.6.3                      py_0  
async-timeout             4.0.1              pyhd3eb1b0_0  
attrs                     21.4.0             pyhd3eb1b0_0  
blas                      1.0                    openblas  
blinker                   1.4             py310h06a4308_0  
brotlipy                  0.7.0           py310h7f8727e_1002  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f8727e_0  
ca-certificates           2022.07.19           h06a4308_0  
cachetools                4.2.2              pyhd3eb1b0_0  
certifi                   2022.9.14       py310h06a4308_0  
cffi                      1.15.1          py310h74dc2b5_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4           py310h06a4308_0  
cryptography              37.0.1          py310h9ce1e76_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
cudnn                     8.4.1.50             hed8a83a_0    conda-forge
dataclasses               0.8                pyh6d0b6a4_7  
flatbuffers               2.0.0                h2531618_0  
frozenlist                1.2.0           py310h7f8727e_1  
gast                      0.4.0              pyhd3eb1b0_0  
giflib                    5.2.1                h7b6447c_0  
google-auth               2.6.0              pyhd3eb1b0_0  
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0  
google-pasta              0.2.0              pyhd3eb1b0_0  
grpc-cpp                  1.47.1               h05bd8bd_6    conda-forge
grpcio                    1.47.1          py310h5b20944_6    conda-forge
h5py                      3.7.0           py310he06866b_0  
hdf5                      1.10.6               h3ffc7dd_1  
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.3                pyhd3eb1b0_0  
importlib-metadata        4.11.3          py310h06a4308_0  
jpeg                      9e                   h7f8727e_0  
keras                     2.10.0             pyhd8ed1ab_0    conda-forge
keras-preprocessing       1.1.2              pyhd3eb1b0_0  
krb5                      1.19.2               hac12032_0  
ld_impl_linux-64          2.38                 h1181459_1  
libabseil                 20220623.0      cxx17_h48a1fff_4    conda-forge
libblas                   3.9.0           15_linux64_openblas    conda-forge
libcblas                  3.9.0           15_linux64_openblas    conda-forge
libcurl                   7.84.0               h91b91d3_0  
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   12.1.0              h8d9b700_16    conda-forge
liblapack                 3.9.0           15_linux64_openblas    conda-forge
libnghttp2                1.46.0               hce63b2e_0  
libopenblas               0.3.20               h043d6bf_1  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.21.6               h6239696_1    conda-forge
libsqlite                 3.39.3               h753d276_0    conda-forge
libssh2                   1.10.0               h8f2d780_0  
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   1.0.3                h7f8727e_2  
libzlib                   1.2.12               h166bdaf_3    conda-forge
markdown                  3.3.4           py310h06a4308_0  
multidict                 5.2.0           py310h5eee18b_3  
nccl                      2.14.3.1             h0800d71_0    conda-forge
ncurses                   6.3                  h5eee18b_3  
numpy                     1.23.1          py310hac523dd_0  
numpy-base                1.23.1          py310h375b286_0  
oauthlib                  3.2.0              pyhd3eb1b0_1  
openssl                   1.1.1q               h7f8727e_0  
opt_einsum                3.3.0              pyhd3eb1b0_1  
packaging                 21.3               pyhd3eb1b0_0  
pip                       22.1.2          py310h06a4308_0  
protobuf                  4.21.6          py310hd8f1fbe_0    conda-forge
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyjwt                     2.4.0           py310h06a4308_0  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.9           py310h06a4308_0  
pysocks                   1.7.1           py310h06a4308_0  
python                    3.10.4               h12debd9_0  
python-flatbuffers        2.0                pyhd3eb1b0_0  
python_abi                3.10                    2_cp310    conda-forge
re2                       2022.06.01           h27087fc_0    conda-forge
readline                  8.1.2                h7f8727e_1  
requests                  2.28.1          py310h06a4308_0  
requests-oauthlib         1.3.0                      py_0  
rsa                       4.7.2              pyhd3eb1b0_1  
scipy                     1.9.1           py310hdfbd76f_0    conda-forge
setuptools                63.4.1          py310h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
snappy                    1.1.9                h295c915_0  
sqlite                    3.39.2               h5082296_0  
tensorboard               2.10.0             pyhd8ed1ab_2    conda-forge
tensorboard-data-server   0.6.0           py310hca6d32c_0  
tensorboard-plugin-wit    1.8.1           py310h06a4308_0  
tensorflow                2.10.0          cuda112py310he87a039_0    conda-forge
tensorflow-base           2.10.0          cuda112py310hf679b68_0    conda-forge
tensorflow-estimator      2.10.0          cuda112py310h2fa73eb_0    conda-forge
termcolor                 1.1.0           py310h06a4308_1  
tk                        8.6.12               h1ccaba5_0  
typing-extensions         4.3.0           py310h06a4308_0  
typing_extensions         4.3.0           py310h06a4308_0  
tzdata                    2022c                h04d1e81_0  
urllib3                   1.26.11         py310h06a4308_0  
werkzeug                  2.0.3              pyhd3eb1b0_0  
wheel                     0.37.1             pyhd3eb1b0_0  
wrapt                     1.14.1          py310h5eee18b_0  
xz                        5.2.5                h7f8727e_1  
yarl                      1.8.1           py310h5eee18b_0  
zipp                      3.8.0           py310h06a4308_0  
zlib                      1.2.12               h5eee18b_3
```

### Environment info

```shell
     active environment : test
    active env location : /home/sacastro/.pyenv/versions/miniconda3-latest/envs/test
            shell level : 1
       user config file : /home/sacastro/.condarc
 populated config files : /home/sacastro/.condarc
          conda version : 4.14.0
    conda-build version : 3.22.0
         python version : 3.9.5.final.0
       virtual packages : __cuda=11.7=0
                          __linux=5.15.0=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/sacastro/.pyenv/versions/miniconda3-latest  (writable)
      conda av data dir : /home/sacastro/.pyenv/versions/miniconda3-latest/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/sacastro/.pyenv/versions/miniconda3-latest/pkgs
                          /home/sacastro/.conda/pkgs
       envs directories : /home/sacastro/.pyenv/versions/miniconda3-latest/envs
                          /home/sacastro/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.27.1 CPython/3.9.5 Linux/5.15.0-48-generic ubuntu/22.04.1 glibc/2.35 solver/libmamba conda-libmamba-solver/22.8.1 libmambapy/0.25.0
                UID:GID : 1000:1000
             netrc file : /home/sacastro/.netrc
           offline mode : False
```

**Comment by bryant1410** [comment]
BTW, note that this command installed `cudatoolkit` 11.3 instead of 11.2

**Comment by hmaarrfk** [comment]
we dont' support mixed channels with `defaults`. please add the conda-forge channel with strict priorities 

https://conda-forge.org/

```
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install <package-name> 
```

and create a new environment.

**Comment by bryant1410** [comment]
Thanks for the prompt response!

I just did the following and I'm still getting the same error:

```bash
conda config --add channels conda-forge
conda config --set channel_priority strict
mamba create -n test2 python tensorflow=2.10
```

<details>
    <summary><code>conda list</code></summary>
<pre class="notranslate">
<code>
# packages in environment at /home/sacastro/.pyenv/versions/miniconda3-latest/envs/test2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   1.2.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.3           py310h5764c6d_0    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.2.0              pyhd8ed1ab_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           py310hff52083_0    conda-forge
cryptography              37.0.4          py310h597c629_0    conda-forge
cudatoolkit               11.7.0              hd8887f6_10    conda-forge
cudnn                     8.4.1.50             hed8a83a_0    conda-forge
flatbuffers               2.0.7                h27087fc_0    conda-forge
frozenlist                1.3.1           py310h5764c6d_0    conda-forge
gast                      0.4.0              pyh9f0ad1d_0    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
google-auth               2.11.1             pyh1a96a4e_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpc-cpp                  1.47.1               h05bd8bd_6    conda-forge
grpcio                    1.47.1          py310h5b20944_6    conda-forge
h5py                      3.7.0           nompi_py310h416281c_101    conda-forge
hdf5                      1.12.2          nompi_h2386368_100    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4          py310hff52083_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
keras                     2.10.0             pyhd8ed1ab_0    conda-forge
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libabseil                 20220623.0      cxx17_h48a1fff_4    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.83.1               h7bff187_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.38               h753d276_0    conda-forge
libprotobuf               3.21.6               h6239696_1    conda-forge
libsqlite                 3.39.3               h753d276_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.12               h166bdaf_3    conda-forge
markdown                  3.4.1              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1           py310h5764c6d_1    conda-forge
multidict                 6.0.2           py310h5764c6d_1    conda-forge
nccl                      2.14.3.1             h0800d71_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.23.3          py310h53a5b5f_0    conda-forge
oauthlib                  3.2.1              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
protobuf                  4.21.6          py310hd8f1fbe_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyjwt                     2.5.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.6          h582c2e5_0_cpython    conda-forge
python-flatbuffers        2.0                pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
re2                       2022.06.01           h27087fc_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
scipy                     1.9.1           py310hdfbd76f_0    conda-forge
setuptools                65.4.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                hbd366e4_1    conda-forge
tensorboard               2.10.0             pyhd8ed1ab_2    conda-forge
tensorboard-data-server   0.6.0           py310h597c629_2    conda-forge
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
tensorflow                2.10.0          cuda112py310he87a039_0    conda-forge
tensorflow-base           2.10.0          cuda112py310hf679b68_0    conda-forge
tensorflow-estimator      2.10.0          cuda112py310h2fa73eb_0    conda-forge
termcolor                 2.0.1              pyhd8ed1ab_1    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022d                h191b570_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
werkzeug                  2.2.2              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.14.1          py310h5764c6d_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yarl                      1.7.2           py310h5764c6d_2    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_3    conda-forge
</code>
</pre>
</details>

<details>
    <summary><code>conda info</code></summary>
<pre class="notranslate">
<code>
     active environment : test2
    active env location : /home/sacastro/.pyenv/versions/miniconda3-latest/envs/test2
            shell level : 1
       user config file : /home/sacastro/.condarc
 populated config files : /home/sacastro/.condarc
          conda version : 4.14.0
    conda-build version : 3.22.0
         python version : 3.9.5.final.0
       virtual packages : __cuda=11.7=0
                          __linux=5.15.0=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/sacastro/.pyenv/versions/miniconda3-latest  (writable)
      conda av data dir : /home/sacastro/.pyenv/versions/miniconda3-latest/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/sacastro/.pyenv/versions/miniconda3-latest/pkgs
                          /home/sacastro/.conda/pkgs
       envs directories : /home/sacastro/.pyenv/versions/miniconda3-latest/envs
                          /home/sacastro/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.27.1 CPython/3.9.5 Linux/5.15.0-48-generic ubuntu/22.04.1 glibc/2.35 solver/libmamba conda-libmamba-solver/22.8.1 libmambapy/0.25.0
                UID:GID : 1000:1000
             netrc file : /home/sacastro/.netrc
           offline mode : False
</code>
</pre>
</details>

Btw:
* Still getting cudatoolkit > 11.2 (11.7)
* Maybe the mixed channel thing can be documented? Can't find it documented.

**Comment by bryant1410** [comment]
Oh, wait, nvm, forgot to activate this other new env.

I'm closing it. But can you please comment on the last "Btw" points?

**Comment by h-vetinari** [comment]
> Still getting cudatoolkit > 11.2 (11.7)

You're getting the cudatoolkit most appropriate for your installed driver (as you can see from `__cuda` in the output of `conda info`).

> Maybe the mixed channel thing can be documented? Can't find it documented.

The instructions that @hmaarrfk posted are on every feedstock & on conda-forge.org, _but_ if it's still unclear it can obviously still be improved. Could you maybe open an issue (or even a PR) at https://github.com/conda-forge/conda-forge.github.io/ what information you'd expect and where you were looking for it?

**Comment by bryant1410** [comment]
> The instructions that @hmaarrfk posted are on every feedstock & on conda-forge.org, _but_ if it's still unclear it can obviously still be improved. Could you maybe open an issue (or even a PR) at https://github.com/conda-forge/conda-forge.github.io/ what information you'd expect and where you were looking for it?

But is it the case for all conda-forge packages that the recommendation is to not mix channels with `defaults`?

**Comment by h-vetinari** [comment]
> But is it the case for all conda-forge packages that the recommendation is to not mix channels with `defaults`?

Yes. 🙃

**Comment by bryant1410** [comment]
I see! But where did you get that from? Where can I read that?

**Comment by h-vetinari** [comment]
> I see! But where did you get that from? Where can I read that?

The strict channel priority stuff is listed on every feedstock because it's not a per-package question. It's just not feasible to test all the possible different ways that packages can be mixed across channels. Even though conda-forge and anaconda use compatible compilers these days, there can be differences (like how certain shared libraries are named, as in this issue), and we cannot reasonably detect this in our CI, and even if we do, we have no way to fix it.

So it gets out-scoped by force of the reality we're in. It might still work some (or even most) of the time, but no guarantees whatsoever. Conda-forge tends to have more packages and faster version upgrades anyway, so there are barely any situations where you'd feel the strict channel priority becoming an issue.

Though let me reiterate the invitation to open an issue about this. I'm obviously too deeply in this to have a neutral POV about how to discover this information, so your experience is useful feedback.

**Comment by h-vetinari** [comment]
PS. If you're not already aware of it, there's a lot of information in the conda-forge [knowledge base](https://conda-forge.org/docs/maintainer/knowledge_base.html).

**Comment by bryant1410** [comment]
> > I see! But where did you get that from? Where can I read that?
> 
> The strict channel priority stuff is listed on every feedstock because it's not a per-package question. It's just not feasible to test all the possible different ways that packages can be mixed across channels. Even though conda-forge and anaconda use compatible compilers these days, there can be differences (like how certain shared libraries are named, as in this issue), and we cannot reasonably detect this in our CI, and even if we do, we have no way to fix it.

I don't understand how the strict channel priority property enforces to only use conda-forge. It could be the case that a transitive dependency is only in `defaults`, right? I mean, not in this package necessarily but for any given conda-forge package.

I can understand the rationale about enforcing not mixing channels, just trying to understand 1) why is across the board for conda-forge, and if so 2) properly document it if it's not documented.

> So it gets out-scoped by force of the reality we're in. It might still work some (or even most) of the time, but no guarantees whatsoever. Conda-forge tends to have more packages and faster version upgrades anyway, so there are barely any situations where you'd feel the strict channel priority becoming an issue.

So you say that it's because of the possible package combination issue? So it's kind of a de-facto standard for package maintainers to use conda-forge only to make sure about the package combination issue? Again, what about the transitive dependencies that aren't in conda-forge?

> PS. If you're not already aware of it, there's a lot of information in the conda-forge [knowledge base](https://conda-forge.org/docs/maintainer/knowledge_base.html).

I wasn't. Thanks!!

**Comment by h-vetinari** [comment]
> Again, what about the transitive dependencies that aren't in conda-forge?

Simple: no package in conda-forge has dependencies outside of conda-forge, and no new such package can be added until all its dependencies are in conda-forge themselves.

> why is across the board for conda-forge

What I described above. Can't test every possible combinations (package X from channel A, package Y from channel B, and the combinatorial explosion that follows) and can't fix packages that are not in our purview/control (i.e. in other channels).

**Comment by bryant1410** [comment]
> Simple: no package in conda-forge has dependencies outside of conda-forge, and no new such package can be added until all its dependencies are in conda-forge themselves.

Oh. Why/how? Where is it enforced?

**Comment by h-vetinari** [comment]
> Where is it enforced?

Infrastructure & the reviews in conda-forge/staged-recipes.

**Comment by maresb** [comment]
Packages are added at [staged-recipes](https://github.com/conda-forge/staged-recipes). In order to be merged and turned into a feedstock so that they can be published on CF, they must build and pass tests. You must pass the tests with CF-only packages. This way, nothing from the outside can creep in.

I agree that there are issues with the CF docs, and somehow in order to get started one somehow needs to acquire lots of folklore.

**Comment by bryant1410** [comment]
I see. Thanks a lot for the info!!!

**Comment by tangyunlong** [comment]
did this error fixed？ I got the same problem，thanks, guys。

**Comment by hmaarrfk** [comment]
Please see: https://github.com/conda-forge/tensorflow-feedstock/issues/275?notification_referrer_id=NT_kwDOAAFfmLA0NDc5NzU3NTIxOjkwMDA4#issuecomment-1258408112

If you are still getting the error and if you think it is not related to the above discussion, please open a new issue providing us with your system information.
