### ISSUE TITLE
checklist for tf 2.11

### ISSUE THREAD

**Issue by ngam** [conda-forge/tensorflow-feedstock#279]
It's coming. We may need a few migrations:

- [x] openssl3 (blocker: https://github.com/conda-forge/tensorboard-data-server-feedstock/pull/13)
- [x] grpc149
- [ ] py311?

cc @conda-forge/tensorflow

**Comment by h-vetinari** [comment]
grpc should be ready to go, but python 3.11 does not look [ready](https://github.com/tensorflow/tensorflow/issues/58032).
