### ISSUE TITLE
Missing `build_estimator.bat` 

### ISSUE THREAD

**Issue by Anselmoo** [conda-forge/tensorflow-feedstock#293]
### Comment:

Can missing `build_estimator.bat` cause trouble in the CI build?

https://github.com/conda-forge/tensorflow-feedstock/blob/f73deb53c2b170ca3116b4faee9e58c4409b6717/recipe/meta.yaml#L261

**Comment by njzjz** [comment]
https://github.com/conda-forge/tensorflow-feedstock/blob/f73deb53c2b170ca3116b4faee9e58c4409b6717/recipe/meta.yaml#L22

The build for windows is skipped at this time, so there is no trouble with what we build.

**Comment by Anselmoo** [comment]
Thx for the quick answer

**Comment by hmaarrfk** [comment]
Just FYI PRs welcome to build windows.
