### ISSUE TITLE
i need python 3.11...

### ISSUE THREAD

**Issue by bjarthur** [conda-forge/tensorflow-feedstock#327]
### Comment:

...and this tensorflow feedstock is holding me back to python 3.10 b/c the latest version of tensorflow that is supported is 2.11.  any plans to support tensorflow >=2.12 so i can get python 3.11?  thanks.

**Comment by hmaarrfk** [comment]
Please see a active ongoing work in PRs

**Comment by bjarthur** [comment]
great!  thanks so much.  should've thought to look there before filing an issue.
