### ISSUE TITLE
TensorFlow: Support CUDA 12

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/tensorflow-feedstock#330]
Depends on issue ( https://github.com/conda-forge/staged-recipes/issues/21382 )

**Comment by jakirkham** [comment]
Not seeing a migrator PR. Though AFAICT it is ready to migrate. Raising an upstream issue ( https://github.com/regro/cf-scripts/issues/1772 ) to see if we can figure out what is happening here

**Comment by jakirkham** [comment]
After digging further looks like this depends on PR ( https://github.com/conda-forge/jaxlib-feedstock/pull/181 )

**Comment by njzjz** [comment]
It looks like https://github.com/tensorflow/tensorflow/commit/d9ee6b59443b5ba0bfde1fcd35b858ffc7e04a66 has removed jax from dependencies. From the error message, it seems that TF does not actually need jax.

**Comment by jakirkham** [comment]
Gotcha. So this will be fixed as part of 2.13.0 ( https://github.com/conda-forge/tensorflow-feedstock/pull/329 )?

**Comment by njzjz** [comment]
Close as resolved by #353.
