### ISSUE TITLE
Is the build broken? not publishing to conda-forge since 2 months

### ISSUE THREAD

**Issue by elgalu** [conda-forge/tensorflow-feedstock#336]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Is the build broken? not publishing to conda-forge since 2 months

### Installed packages

```shell
latest version is 2.14.0
```

### Environment info

```shell
conda-forge version is 2.12.1
```

**Comment by hmaarrfk** [comment]
See activity in pull requests.
https://github.com/conda-forge/tensorflow-feedstock/pull/329

tensorflow is hard to build.

help is welcome. you can always fork from where others have left off and give it your own try!
