### ISSUE TITLE
tensorflow v2.10.1 availability?

### ISSUE THREAD

**Issue by rpetit3** [conda-forge/tensorflow-feedstock#339]
### Comment:

Hello,

Would it be possible to get a build for tensorflow v2.10.1 made available? I realize its been out for a while, but I'm getting my but kicked over at https://github.com/bioconda/bioconda-recipes/pull/41417 with the solver related to v2.10 on a tool that only supports 2.10. 

I'd be happy to submit a PR, or reopening https://github.com/conda-forge/tensorflow-feedstock/pull/283 is another option. 

Thank you so much!
Robert

**Comment by h-vetinari** [comment]
Have a look [here](https://github.com/conda-forge/tensorflow-feedstock/pull/297#issuecomment-1383790671) for a related situation/discussion. I suggest you open a pull request that:
* first does a single commit to hard-reset to #283 
* then, make all the necessary changes on top so the package compiles (at least until the 6h timeout)
* if you manage step two, I'll create a branch for 2.10 and we retarget your PR to that (dropping the commit from step 1)

**Comment by rpetit3** [comment]
Thank you @h-vetinari looking into the related situation/discussion, I'm going to close this for now. I'll do some testing on the medaka tool first before adventuring down the reviving v2.10.1 path

Thanks again for the quick response!
