### ISSUE TITLE
Is this version compiled with SSE4, AVX etc.

### ISSUE THREAD

**Issue by jhmenke** [conda-forge/tensorflow-feedstock#34]
Hello,

when i install tensorflow via "conda install tensorflow", running scripts with it display several warnings about possible optimizations. These would speed up tensorflow significantly and i think are supported by many modern CPUs.

Does this version have SSE etc. enabled?

**Comment by jakirkham** [comment]
We do not compile this package from source currently. We repackage Google's wheels on [PyPI]( https://pypi.python.org/pypi/tensorflow ). So you would have to ask them how they build it.

**Comment by jhmenke** [comment]
For anyone wondering: The pypi package is built without optimizations. (as of right now)

**Comment by jakirkham** [comment]
Thanks for the info.

We have attempted to build this from source and likely will again. That said, we still need to come up with some acceptable set of assembly instructions that will run on a range of hardware. Unless Tensorflow has some way of determining what the hardware can support at runtime, this will likely mean not having every optimization enabled. Though there will at least be a recipe that one can tweak and room for discussing how better to handle additional instructions in a reasonable way.

xref: https://github.com/conda-forge/tensorflow-feedstock/pull/12
xref: https://github.com/conda-forge/conda-forge.github.io/issues/49

**Comment by jjhelmus** [comment]
Tensorflow does not have dynamic code paths based on CPU capabilities.  Whatever target micro-architecture is selected at build time is the minimum CPU version required at run time.  Starting with the 1.5.1 release, the wheels available on PyPI use AVX instructions.  We are re-packaging the wheels for the conda package so these have the same AVX requirements.

If you need conda packages which do not require AVX the conda packages in `defaults` are built from source and should work on nearly all x86_64 CPUs.

**Comment by pkgw** [comment]
@jjhelmus Ah, good to know that the `defaults` packages don't require AVX.

**Comment by dailybudushu** [comment]
But I can't tell which packages require AVX .
