### ISSUE TITLE
Release 1.2

### ISSUE THREAD

**Issue by hajapy** [conda-forge/tensorflow-feedstock#35]
Tensorflow 1.2 has been released: https://github.com/tensorflow/tensorflow/releases

Looking through the requirements for the [pypi wheels](https://pypi.python.org/pypi/tensorflow), I noticed a possible issue. This release brings in bleach 1.5.0 and html5lib (==0.9999999) and on conda-forge we are missing a build for this exact release of html5lib. So it looks like we need to build an old version on the html5lib feedstock if we want working run requirements for the tensorflow 1.2 recipe. 

As far as I can tell, this bleach / html5lib requirement only serves one feature of tensorboard: https://github.com/tensorflow/tensorboard/blob/f024dc5078f68cb926a4c341eeabc5679afa29cb/tensorboard/plugins/text/text_plugin.py

**Comment by adrianchia** [comment]
I think backports.weakref is also missing

**Comment by hajapy** [comment]
You're right, thanks for opening the PR at staged-recipes. Should help us get to 1.2 sooner :)
