### ISSUE TITLE
What CUDA packages are needed to run on GPU?

### ISSUE THREAD

**Issue by sh-shahrokhi** [conda-forge/tensorflow-feedstock#358]
Hello.

What is the recommended instruction to run TensorFlow on GPU? Which version of cuda-toolkit or other packages are needed. Is it necessary set to any environment variable?

Thanks.

**Comment by hmaarrfk** [comment]
This may be related to the issues observed in: 
https://github.com/conda-forge/tensorflow-feedstock/issues/365

**Comment by sh-shahrokhi** [comment]
Yes. I installed the cuda packages that come with tensorflow, but it didn't
recognize gpu.

**Comment by hmaarrfk** [comment]
I’m going to close this issue since you didn’t include critical information that is requested in our template. If you think it is different than the other issue I referenced, please open a new issue and provide all requested information about your environment. 

Happy new year!
