### ISSUE TITLE
Tensorflow not installing for python2.7

### ISSUE THREAD

**Issue by cryptox31** [conda-forge/tensorflow-feedstock#37]
Can someone tell me how do I install Tensorflow for python2.7 using conda.
Everytime I try installing it, it gets installed from python3.*

**Comment by jakirkham** [comment]
Is this on Windows? If so, there is no Python 2.7 package.

**Comment by cryptox31** [comment]
This is Ubuntu 16.04, Power 8

**Comment by hajapy** [comment]
does `conda create -n tfpy27 -c conda-forge python=2 tensorflow` do what you want? are you installing in an environment that is already on python 3 or installing with other packages that require python 3?

**Comment by cryptox31** [comment]
I am installing in an environment that is already on python3. I need python 2.7 because some python scripts work only with python2.7 and not 3.*.*. Also could you tell if this would install the tensorflow-gpu version or just the cpu one?

**Comment by jakirkham** [comment]
So you would need to downgrade your `python` version first.

**Comment by cryptox31** [comment]
Yes I did that. Now it works on python2
could you tell if this would install the tensorflow-gpu version or just the cpu one?

**Comment by hajapy** [comment]
This feedstock is for the cpu package, we do not yet have a gpu package: https://github.com/conda-forge/tensorflow-feedstock/issues/10

You can pip install tensorflow-gpu into your conda env.

**Comment by cryptox31** [comment]
@hajapy It gives me
 `Could not find a version that satisfies the requirement tensorflow-gpu (from versions: )
No matching distribution found for tensorflow-gpu`
Maybe because my ubuntu16.04 runs on ppc64el architecture (Power 8). 
Could you tell me how can install tensorflow-gpu without pip?

**Comment by hajapy** [comment]
I think this conda package may be your easiest solution: https://anaconda.org/anaconda/tensorflow-gpu
`conda install -c anaconda tensorflow-gpu=1.1.0`

For newer versions or for platform specific builds, you will have to consider building from source: https://www.tensorflow.org/install/install_source

**Comment by shwetagargade216** [comment]
I'm getting same problem and im using windows , python2.7 version and doing in vertual env of python 2.7

**Comment by jjhelmus** [comment]
Tensorflow does not support Python 2.7 on Windows.

**Comment by shwetagargade216** [comment]
For tensorflow > 1.1  and python 2.7(or vertual env of python 2.7)  which ubantu verion needed.

**Comment by Linranran** [comment]
@hajapy  why i can not sucess with 
conda create -n tfpy27 -c conda-forge python=2 tensorflow   in windows10 with python2.7   as Erivca
