### ISSUE TITLE
Viability of protouf and ABSEIL shared linkages

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/tensorflow-feedstock#378]
### Comment:

My environments, requiring the co-installation of opencv + tensorflow have recently had a hard time getting "updated" since the protobuf/absl migrations of tensorflow typically lag.

This isn't from the lack of trying, but more from the fact that it seems that tensorflow uses protobuf and absl in unique ways and don't often make it easy to link them in a share fashion.

I'm wondering if we could:

1. start doing dual protobuf migrations. This would really release  the pressure of constantly trying to keep up with the latest tensorflow and latest protobufs.
2. go back to static built-in versions of protobuf for tensorflow
3. Other ideas.

Anyway, I just wanted to raise my concerns for sustainability on this front.

cc: @h-vetinari @xhochy for being the two heavily involved individuals on this front.

**Comment by h-vetinari** [comment]
> go back to static built-in versions of protobuf for tensorflow

I could live with that (tensorflow is hard enough to build...), as long as we can make reasonably sure that no protobuf types appear in the C API.

**Comment by hmaarrfk** [comment]
>  as long as we can make reasonably sure that no protobuf types appear in the C API.

would we look at the output of nm?

**Comment by xhochy** [comment]
Something like `nm | grep ' T ' | grep protobuf`?

**Comment by hmaarrfk** [comment]
i'm still concerned, but not enough to do anything about this at this moment

**Comment by hmaarrfk** [comment]
As of today, tensorflow is one of the few packages in my stack that requires abseil 20240722.

This is really draining.

Even though many of us are trying:
https://github.com/conda-forge/tensorflow-feedstock/pull/437

it is now holding up other PRs from getting the review they need:
https://github.com/conda-forge/tensorflow-feedstock/pull/438

**Comment by h-vetinari** [comment]
I won't stand in the way of revendoring

**Comment by hmaarrfk** [comment]
The question always was for me. Does the initialization routine clash between a static library of one version and a dynamic one of a different one.
