### ISSUE TITLE
No tensorboard after update to 1.3.0

### ISSUE THREAD

**Issue by sdvillal** [conda-forge/tensorflow-feedstock#42]
The last update breaks tensorboard, as it is out of the tensorflow distribution since 1.3.0. There are a couple of options to get it back:

- Add a tensorboard recipe ([here my attempt](https://github.com/conda-forge/staged-recipes/pull/3866)).
- Include tensorboard back in this package (either by removing --no-deps or installing explicitly tensorflow-tensorboard from pypi).

I think adding a tensorboard package to conda-forge is the best way to go, so I would appreciate any comments on my PR.

**Comment by jjhelmus** [comment]
Packing up `tensorflow-tensorboard` is a great idea.  From my testing building from source is difficult, it requires bazel and at least Ubunutu 14.04 to run a binary `protoc` executable downloaded during the build.  This seems quite involved for a pure Python package with a zip file containing two html files. Re-packaging the whl is likely the best option.

I don't believe it is necessary to include `tensorboard` in the `tensorflow` package itself.  My recommendation would be to have the `tensorflow` package have a run time requirement on `tensorflow-tensorboard`.  This is how PyPI declairs the dependencies, `tensorflow` and `tensorflow-gpu` require `tensorflow-tensorboard`.

**Comment by sdvillal** [comment]
The problem of having tensorflow to depend on tensorboard is that, actually, the dependency is inverse - tensorflow does not need tensorboard, but tensorboard does need tensorflow. So following google here has some drawbacks.

I wrote this in my PR: Note that, as opposed to the wheels, this package makes explicit that tensorboard requires tensorflow to work, and not the other way round. Right now the tensorboard package in pypi does the opposite, which is incorrect, making the pypi tensorboard package non-standalone - you can install it and yet not have a working version of tensorboard. I think this little breakage has happened because google priority was not to surprise people expecting to have tensorboard right away after installing tensorflow. The decision was then to make tensorboard a dependency for tensorflow and, to avoid cyclic dependencies and all kind of problems with double installations and file clobbing, to make tensorboard not to depend on tensorflow. Hopefully they will solve this better in future releases.

**Comment by sdvillal** [comment]
There is now a tensorboard package in conda-forge.

**Comment by jakirkham** [comment]
Thanks @sdvillal.
