### ISSUE TITLE
Tensorflow installation issue

### ISSUE THREAD

**Issue by waveroarer** [conda-forge/tensorflow-feedstock#44]
I typed the following in the Anaconda Prompt
"conda create --name=IntroToTensorFlow python=3 anaconda
source activate IntroToTensorFlow
conda install -c conda-forge tensorflow"

Then it shows

"Packages missing in current channels:
- tensorflow

http://conda.anaconda.org/conda-forge/win-32
http://conda.anaconda.org/conda-forge/noarch
http://repo.continuum.io/pkgs/main/win-32
http://repo.continuum.io/pkgs/main/noarch
http://repo.continuum.io/pkgs/free/win-32
http://repo.continuum.io/pkgs/free/noarch
http://repo.continuum.io/pkgs/r/win-32
http://repo.continuum.io/pkgs/r/noarch
http://repo.continuum.io/pkgs/pro/win-32
http://repo.continuum.io/pkgs/pro/noarch
http://repo.continuum.io/pkgs/msys2/win-32
http://repo.continuum.io/pkgs/msys2/noarch"

**Comment by jjhelmus** [comment]
You appear to be using Anaconda for win-32.  Tensorflow is only available for the win-64 platform.  Can you use the 64-bit Windows installer?
