### ISSUE TITLE
No Module named tensorflow.tensorboard

### ISSUE THREAD

**Issue by AustinT** [conda-forge/tensorflow-feedstock#48]
I installed tensorflow/tensorboard yesterday using:

`conda install -c conda-forge tensorflow`

Tensorflow works fine but tensorboard does not work. Here is my code from the command line:

```
C:\Users\Austin>tensorboard --logdir="C:\Users\Austin\Desktop\handson-ml\tf_logs"  
Traceback (most recent call last):  
  File "C:\ProgramData\Anaconda3\Scripts\tensorboard-script.py", line 3, in <module>  
    import tensorflow.tensorboard.tensorboard  
ModuleNotFoundError: No module named 'tensorflow.tensorboard'
```

I believe the issue is that the line `import tensorflow.tensorboard.tensorboard` in _tensorboard-script.py_ needs to be edited because it refers to the old tensorflow structure where tensorboard was not its own package, but I am not sure exactly what it should be changed to. Any help would be greatly appreciated.

## System information
- Windows 10
- Python 3.6 (via Anaconda)
- Tensorflow version 1.4.0 (default latest)

*Note:* I also had this issue on my other PC, but uninstalling it and installing via pip as outlined on the tensorflow website worked. (https://www.tensorflow.org/install/install_windows)

**Comment by gilbertfrancois** [comment]
Please update to version 1.8.0. The issue has been resolved.

**Comment by dougalsutherland** [comment]
(Note that the builds for 1.8 aren't quite online yet, but should be in the next few hours.)
