### ISSUE TITLE
Where did 1.7 go?

### ISSUE THREAD

**Issue by oxinabox** [conda-forge/tensorflow-feedstock#56]
Two weeks ago when I made https://github.com/malmaud/TensorFlow.jl/pull/386
<s> there was tensorflow 1.7.0 from Conda Forge. </s>

According to https://github.com/malmaud/TensorFlow.jl/pull/396
it does not <s>anymore.</s>

Which is supported by it not showing up on 
https://anaconda.org/conda-forge/tensorflow/files

**Comment by oxinabox** [comment]
Well I thought I was hitting conda-forge but maybe I was hitting 
https://anaconda.org/anaconda/tensorflow/files

If so, it would be good to have a conda-forge version.

**Comment by dougalsutherland** [comment]
We missed 1.7 and went straight to 1.8 (guess the update bot doesn't work for this recipe). Is there a reason you need 1.7 in particular?

**Comment by oxinabox** [comment]
Their was but  it is now resolved
