### ISSUE TITLE
Build tensorflow from source not whl files.

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/tensorflow-feedstock#6]
Currently the tensorflow recipe is repackaging the whl files provided by Google into conda packages.  The whl files link against a newer version of glibc which limited what Linux distribution that the conda package works on and are only available for Python 2.7 and 3.4 on Linux.

A "better" solution would be to build the package from source, but this requires installing [Bazel](http://bazel.io/) which [requires Java JDK 8](http://bazel.io/docs/install.html).  I have successfully built a conda package for 0.8.0 from source using a [Ubunutu 14.04 Docker container](https://github.com/jjhelmus/wip_conda_recipes/tree/master/tensorflow) with Java+Bazel.  We could do the same here but it would require quite a bit of customization of this feedstock.  Anyone have opinion on this topic?

**Comment by rgommers** [comment]
There's 3 people reporting at https://github.com/numpy/numpy/issues/8076 that installing ``tensorflow`` breaks numpy, and it looks related to this wheel repackaging business.

**Comment by rgommers** [comment]
[This comment](https://github.com/scipy/scipy.org/pull/179#issuecomment-247179912) says that indeed tensorflow pulls in a numpy wheel somehow. So that's pretty badly broken.

**Comment by jakirkham** [comment]
Ouch! Yeah the build situation here is not great. It is unfortunately quite difficult to build `tensorflow` from source. That said, @jjhelmus added `bazel` recently (merged today), which should help.

**Comment by hajapy** [comment]
I'm a little confused, our build recipe installs tensorflow wheel via pip with --no-deps, so the only numpy should be one specified by the meta.yaml run time requirements.

**Comment by rgommers** [comment]
I also don't really understand it, but it's reported by 4 people so should be reproducible.

**Comment by jakirkham** [comment]
Of course, I think it is more surprise at the issue's existence than any doubt that people are running into an issue. Though you make a good point, steps to reproduce the issue would be very helpful in debugging it. Was that in the issue and I simply missed it?

**Comment by rgommers** [comment]
No, they all said "installed tensorflow with conda, then numpy broke". Asked for exact install commands.

**Comment by jakirkham** [comment]
Great, thanks Ralf.

**Comment by pgunn** [comment]
Is it possible to copy the build instructions from the non-conda-forge builds of tensorflow? Those versions don't seem to have the GLIBC version dependency (tested on RHEL7, which has a very dated glibc).

**Comment by jakirkham** [comment]
There is some work for this in PR ( https://github.com/conda-forge/tensorflow-feedstock/pull/69 ). That said, this is not easy work. So please feel free to chip in if it is of interest and you have cycles.

**Comment by jjhelmus** [comment]
Done in #74
