### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/tensorflow-feedstock#65]
What is the status of Python 3.7 for this recipe?

**Comment by jjhelmus** [comment]
Upstream does not yet support Python 3.7, see tensorflow/tensorflow#20517.  The 1.13 release looks like it will add support.

**Comment by asmeurer** [comment]
Thanks.

**Comment by kyleabeauchamp** [comment]
FYI I've started a PR to upgrade 1.13 and enable py37: https://github.com/conda-forge/tensorflow-feedstock/pull/66

There are still a few more kinks to work out in that PR.  Just need to work out the final kinks and wait for the final tf 1.13 to release.

**Comment by jjhelmus** [comment]
Python 3.7 builds have been out since the 1.13 release.  Closing.
