### ISSUE TITLE
TF 1.14rc and 2.0b not on conda-forge

### ISSUE THREAD

**Issue by bionicles** [conda-forge/tensorflow-feedstock#70]
Issue: cannot locate tensorflow 1.14rc or 2.0b on conda-forge

these new versions have critical new layers and features, but are not on conda forge, but when you install with pip, it breaks...

we really need conda support for the latest versions of tensorflow because deep learning is a priority for many companies

**Comment by sangramga** [comment]
Tensorflow 1.14.0 is also released. [https://github.com/tensorflow/tensorflow/releases/tag/v1.14.0](https://github.com/tensorflow/tensorflow/releases/tag/v1.14.0). Please provide support for the same.

**Comment by cc20002002** [comment]
please include 1.14, preferably with intel optimisation

**Comment by isuruf** [comment]
If it is a priority for you, please consider sending a PR.

**Comment by theroggy** [comment]
Starting to trail a lot on the latest versions of tensorflow... and combining with the more recent versions available on the anaconda channel breaks different dependencies with other packages (eg. geopandas)... 

Would be great if there would be an update to tensorflow 2.2...

**Comment by xhochy** [comment]
Closing as we have now tensorflow 2.4.0 with #110
